/* HASHROOTPBILL */
export const HASHROOTPBILL_LIST = 'HASHROOTPBILL_LIST';
export const HASHROOTPBILL_LIST_SUCCESS = 'HASHROOTPBILL_LIST_SUCCESS';
export const HASHROOTPBILL_LIST_FAILED = 'HASHROOTPBILL_LIST_FAILED';

export const HASHROOTPBILL_ADD = 'HASHROOTPBILL_ADD';
export const HASHROOTPBILL_ADD_SUCCESS = 'HASHROOTPBILL_ADD_SUCCESS';
export const HASHROOTPBILL_ADD_FAILED = 'HASHROOTPBILLADD_ADD_FAILED';

export const HASHROOTPBILL_UPDATE = 'HASHROOTPBILL_UPDATE';
export const HASHROOTPBILL_UPDATE_SUCCESS = 'HASHROOTPBILL_UPDATE_SUCCESS';
export const HASHROOTPBILL_UPDATE_FAILED = 'HASHROOTPBILL_UPDATE_FAILED';

export const HASHROOTPBILL_DELETE = 'HASHROOTPBILL_DELETE';
export const HASHROOTPBILL_DELETE_SUCCESS = 'HASHROOTPBILL_DELETE_SUCCESS';
export const HASHROOTPBILL_DELETE_FAILED = 'HASHROOTPBILLADD_DELETE_FAILED';

export const HASHROOTPBILL_CLONE = 'HASHROOTPBILL_CLONE';
export const HASHROOTPBILL_CLONE_SUCCESS = 'HASHROOTPBILL_CLONE_SUCCESS';
export const HASHROOTPBILL_CLONE_FAILED = 'HASHROOTPBILL_CLONE_FAILED';

export const HASHROOTPBILL_DOWNLOAD_BILL = 'HASHROOTPBILL_DOWNLOAD_BILL';
export const HASHROOTPBILL_DOWNLOAD_BILL_SUCCESS = 'HASHROOTPBILL_DOWNLOAD_BILL_SUCCESS';
export const HASHROOTPBILL_DOWNLOAD_BILL_FAILED = 'HASHROOTPBILL_DOWNLOAD_BILL_FAILED';
