/* HASHROOTBILL */
export const HASHROOTBILL_LIST = 'HASHROOTBILL_LIST';
export const HASHROOTBILL_LIST_SUCCESS = 'HASHROOTBILL_LIST_SUCCESS';
export const HASHROOTBILL_LIST_FAILED = 'HASHROOTBILL_LIST_FAILED';

export const HASHROOTBILL_ADD = 'HASHROOTBILL_ADD';
export const HASHROOTBILL_ADD_SUCCESS = 'HASHROOTBILL_ADD_SUCCESS';
export const HASHROOTBILL_ADD_FAILED = 'HASHROOTBILLADD_ADD_FAILED';

export const HASHROOTBILL_UPDATE = 'HASHROOTBILL_UPDATE';
export const HASHROOTBILL_UPDATE_SUCCESS = 'HASHROOTBILL_UPDATE_SUCCESS';
export const HASHROOTBILL_UPDATE_FAILED = 'HASHROOTBILL_UPDATE_FAILED';

export const HASHROOTBILL_DELETE = 'HASHROOTBILL_DELETE';
export const HASHROOTBILL_DELETE_SUCCESS = 'HASHROOTBILL_DELETE_SUCCESS';
export const HASHROOTBILL_DELETE_FAILED = 'HASHROOTBILLADD_DELETE_FAILED';

export const HASHROOTBILL_CLONE = 'HASHROOTBILL_CLONE';
export const HASHROOTBILL_CLONE_SUCCESS = 'HASHROOTBILL_CLONE_SUCCESS';
export const HASHROOTBILL_CLONE_FAILED = 'HASHROOTBILL_CLONE_FAILED';

export const HASHROOTBILL_DOWNLOAD_BILL = 'HASHROOTBILL_DOWNLOAD_BILL';
export const HASHROOTBILL_DOWNLOAD_BILL_SUCCESS = 'HASHROOTBILL_DOWNLOAD_BILL_SUCCESS';
export const HASHROOTBILL_DOWNLOAD_BILL_FAILED = 'HASHROOTBILL_DOWNLOAD_BILL_FAILED';
