/* HASHROOTPINVOICE */
export const HASHROOTPINVOICE_LIST = 'HASHROOTPINVOICE_LIST';
export const HASHROOTPINVOICE_LIST_SUCCESS = 'HASHROOTPINVOICE_LIST_SUCCESS';
export const HASHROOTPINVOICE_LIST_FAILED = 'HASHROOTPINVOICE_LIST_FAILED';

export const HASHROOTPINVOICE_ADD = 'HASHROOTPINVOICE_ADD';
export const HASHROOTPINVOICE_ADD_SUCCESS = 'HASHROOTPINVOICE_ADD_SUCCESS';
export const HASHROOTPINVOICE_ADD_FAILED = 'HASHROOTPINVOICEADD_ADD_FAILED';

export const HASHROOTPINVOICE_UPDATE = 'HASHROOTPINVOICE_UPDATE';
export const HASHROOTPINVOICE_UPDATE_SUCCESS = 'HASHROOTPINVOICE_UPDATE_SUCCESS';
export const HASHROOTPINVOICE_UPDATE_FAILED = 'HASHROOTPINVOICE_UPDATE_FAILED';

export const HASHROOTPINVOICE_DELETE = 'HASHROOTPINVOICE_DELETE';
export const HASHROOTPINVOICE_DELETE_SUCCESS = 'HASHROOTPINVOICE_DELETE_SUCCESS';
export const HASHROOTPINVOICE_DELETE_FAILED = 'HASHROOTPINVOICEADD_DELETE_FAILED';

export const HASHROOTPINVOICE_CLONE = 'HASHROOTPINVOICE_CLONE';
export const HASHROOTPINVOICE_CLONE_SUCCESS = 'HASHROOTPINVOICE_CLONE_SUCCESS';
export const HASHROOTPINVOICE_CLONE_FAILED = 'HASHROOTPINVOICE_CLONE_FAILED';

export const HASHROOTPINVOICE_DOWNLOAD_INVOICE = 'HASHROOTPINVOICE_DOWNLOAD_INVOICE';
export const HASHROOTPINVOICE_DOWNLOAD_INVOICE_SUCCESS = 'HASHROOTPINVOICE_DOWNLOAD_INVOICE_SUCCESS';
export const HASHROOTPINVOICE_DOWNLOAD_INVOICE_FAILED = 'HASHROOTPINVOICE_DOWNLOAD_INVOICE_FAILED';
