/* HASHROOTSSBILL */
export const HASHROOTSSBILL_LIST = 'HASHROOTSSBILL_LIST';
export const HASHROOTSSBILL_LIST_SUCCESS = 'HASHROOTSSBILL_LIST_SUCCESS';
export const HASHROOTSSBILL_LIST_FAILED = 'HASHROOTSSBILL_LIST_FAILED';

export const HASHROOTSSBILL_ADD = 'HASHROOTSSBILL_ADD';
export const HASHROOTSSBILL_ADD_SUCCESS = 'HASHROOTSSBILL_ADD_SUCCESS';
export const HASHROOTSSBILL_ADD_FAILED = 'HASHROOTSSBILLADD_ADD_FAILED';

export const HASHROOTSSBILL_UPDATE = 'HASHROOTSSBILL_UPDATE';
export const HASHROOTSSBILL_UPDATE_SUCCESS = 'HASHROOTSSBILL_UPDATE_SUCCESS';
export const HASHROOTSSBILL_UPDATE_FAILED = 'HASHROOTSSBILL_UPDATE_FAILED';

export const HASHROOTSSBILL_DELETE = 'HASHROOTSSBILL_DELETE';
export const HASHROOTSSBILL_DELETE_SUCCESS = 'HASHROOTSSBILL_DELETE_SUCCESS';
export const HASHROOTSSBILL_DELETE_FAILED = 'HASHROOTSSBILLADD_DELETE_FAILED';

export const HASHROOTSSBILL_CLONE = 'HASHROOTSSBILL_CLONE';
export const HASHROOTSSBILL_CLONE_SUCCESS = 'HASHROOTSSBILL_CLONE_SUCCESS';
export const HASHROOTSSBILL_CLONE_FAILED = 'HASHROOTSSBILL_CLONE_FAILED';

export const HASHROOTSSBILL_DOWNLOAD_BILL = 'HASHROOTSSBILL_DOWNLOAD_BILL';
export const HASHROOTSSBILL_DOWNLOAD_BILL_SUCCESS = 'HASHROOTSSBILL_DOWNLOAD_BILL_SUCCESS';
export const HASHROOTSSBILL_DOWNLOAD_BILL_FAILED = 'HASHROOTSSBILL_DOWNLOAD_BILL_FAILED';
