/* HASHROOTSSINVOICE */
export const HASHROOTSSINVOICE_LIST = 'HASHROOTSSINVOICE_LIST';
export const HASHROOTSSINVOICE_LIST_SUCCESS = 'HASHROOTSSINVOICE_LIST_SUCCESS';
export const HASHROOTSSINVOICE_LIST_FAILED = 'HASHROOTSSINVOICE_LIST_FAILED';

export const HASHROOTSSINVOICE_ADD = 'HASHROOTSSINVOICE_ADD';
export const HASHROOTSSINVOICE_ADD_SUCCESS = 'HASHROOTSSINVOICE_ADD_SUCCESS';
export const HASHROOTSSINVOICE_ADD_FAILED = 'HASHROOTSSINVOICEADD_ADD_FAILED';

export const HASHROOTSSINVOICE_UPDATE = 'HASHROOTSSINVOICE_UPDATE';
export const HASHROOTSSINVOICE_UPDATE_SUCCESS = 'HASHROOTSSINVOICE_UPDATE_SUCCESS';
export const HASHROOTSSINVOICE_UPDATE_FAILED = 'HASHROOTSSINVOICE_UPDATE_FAILED';

export const HASHROOTSSINVOICE_DELETE = 'HASHROOTSSINVOICE_DELETE';
export const HASHROOTSSINVOICE_DELETE_SUCCESS = 'HASHROOTSSINVOICE_DELETE_SUCCESS';
export const HASHROOTSSINVOICE_DELETE_FAILED = 'HASHROOTSSINVOICEADD_DELETE_FAILED';

export const HASHROOTSSINVOICE_CLONE = 'HASHROOTSSINVOICE_CLONE';
export const HASHROOTSSINVOICE_CLONE_SUCCESS = 'HASHROOTSSINVOICE_CLONE_SUCCESS';
export const HASHROOTSSINVOICE_CLONE_FAILED = 'HASHROOTSSINVOICE_CLONE_FAILED';

export const HASHROOTSSINVOICE_DOWNLOAD_INVOICE = 'HASHROOTSSINVOICE_DOWNLOAD_INVOICE';
export const HASHROOTSSINVOICE_DOWNLOAD_INVOICE_SUCCESS = 'HASHROOTSSINVOICE_DOWNLOAD_INVOICE_SUCCESS';
export const HASHROOTSSINVOICE_DOWNLOAD_INVOICE_FAILED = 'HASHROOTSSINVOICE_DOWNLOAD_INVOICE_FAILED';
