/* HASHROOTSINVOICE */
export const HASHROOTSINVOICE_LIST = 'HASHROOTSINVOICE_LIST';
export const HASHROOTSINVOICE_LIST_SUCCESS = 'HASHROOTSINVOICE_LIST_SUCCESS';
export const HASHROOTSINVOICE_LIST_FAILED = 'HASHROOTSINVOICE_LIST_FAILED';

export const HASHROOTSINVOICE_ADD = 'HASHROOTSINVOICE_ADD';
export const HASHROOTSINVOICE_ADD_SUCCESS = 'HASHROOTSINVOICE_ADD_SUCCESS';
export const HASHROOTSINVOICE_ADD_FAILED = 'HASHROOTSINVOICEADD_ADD_FAILED';

export const HASHROOTSINVOICE_UPDATE = 'HASHROOTSINVOICE_UPDATE';
export const HASHROOTSINVOICE_UPDATE_SUCCESS = 'HASHROOTSINVOICE_UPDATE_SUCCESS';
export const HASHROOTSINVOICE_UPDATE_FAILED = 'HASHROOTSINVOICE_UPDATE_FAILED';

export const HASHROOTSINVOICE_DELETE = 'HASHROOTSINVOICE_DELETE';
export const HASHROOTSINVOICE_DELETE_SUCCESS = 'HASHROOTSINVOICE_DELETE_SUCCESS';
export const HASHROOTSINVOICE_DELETE_FAILED = 'HASHROOTSINVOICEADD_DELETE_FAILED';

export const HASHROOTSINVOICE_CLONE = 'HASHROOTSINVOICE_CLONE';
export const HASHROOTSINVOICE_CLONE_SUCCESS = 'HASHROOTSINVOICE_CLONE_SUCCESS';
export const HASHROOTSINVOICE_CLONE_FAILED = 'HASHROOTSINVOICE_CLONE_FAILED';

export const HASHROOTSINVOICE_DOWNLOAD_INVOICE = 'HASHROOTSINVOICE_DOWNLOAD_INVOICE';
export const HASHROOTSINVOICE_DOWNLOAD_INVOICE_SUCCESS = 'HASHROOTSINVOICE_DOWNLOAD_INVOICE_SUCCESS';
export const HASHROOTSINVOICE_DOWNLOAD_INVOICE_FAILED = 'HASHROOTSINVOICE_DOWNLOAD_INVOICE_FAILED';
