/* HASHROOTINVOICE */
export const HASHROOTINVOICE_LIST = 'HASHROOTINVOICE_LIST';
export const HASHROOTINVOICE_LIST_SUCCESS = 'HASHROOTINVOICE_LIST_SUCCESS';
export const HASHROOTINVOICE_LIST_FAILED = 'HASHROOTINVOICE_LIST_FAILED';

export const HASHROOTINVOICE_ADD = 'HASHROOTINVOICE_ADD';
export const HASHROOTINVOICE_ADD_SUCCESS = 'HASHROOTINVOICE_ADD_SUCCESS';
export const HASHROOTINVOICE_ADD_FAILED = 'HASHROOTINVOICEADD_ADD_FAILED';

export const HASHROOTINVOICE_UPDATE = 'HASHROOTINVOICE_UPDATE';
export const HASHROOTINVOICE_UPDATE_SUCCESS = 'HASHROOTINVOICE_UPDATE_SUCCESS';
export const HASHROOTINVOICE_UPDATE_FAILED = 'HASHROOTINVOICE_UPDATE_FAILED';

export const HASHROOTINVOICE_DELETE = 'HASHROOTINVOICE_DELETE';
export const HASHROOTINVOICE_DELETE_SUCCESS = 'HASHROOTINVOICE_DELETE_SUCCESS';
export const HASHROOTINVOICE_DELETE_FAILED = 'HASHROOTINVOICEADD_DELETE_FAILED';

export const HASHROOTINVOICE_CLONE='HASHROOTINVOICE_CLONE';
export const HASHROOTINVOICE_CLONE_SUCCESS='HASHROOTINVOICE_CLONE_SUCCESS';
export const HASHROOTINVOICE_CLONE_FAILED='HASHROOTINVOICE_CLONE_FAILED';
// export const HASHROOTINVOICE_DOWNLOAD_INVOICE='HASHROOTINVOICE_DOWNLOAD_INVOICE';
// export const HASHROOTINVOICE_DOWNLOAD_INVOICE_SUCCESS='HASHROOTINVOICE_DOWNLOAD_INVOICE_SUCCESS';
// export const HASHROOTINVOICE_DOWNLOAD_INVOICE_FAILED='HASHROOTINVOICE_DOWNLOAD_INVOICE_FAILED';
