/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

export const LOGOUT_USER = 'LOGOUT_USER';

export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAILED = 'FORGET_PASSWORD_FAILED';


export const COUNTRIES_LIST = 'COUNTRIES_LIST';
export const COUNTRIES_LIST_SUCCESS = 'COUNTRIES_LIST_SUCCESS';
export const COUNTRIES_LIST_FAILED = 'COUNTRIES_LIST_FAILED';

export const PAYMENT_LIST = 'PAYMENT_LIST';
export const PAYMENT_LIST_SUCCESS = 'PAYMENT_LIST_SUCCESS';
export const PAYMENT_LIST_FAILED = 'PAYMENT_LIST_FAILED';

export const HSN_LIST = 'HSN_LIST';
export const HSN_LIST_SUCCESS = 'HSN_LIST_SUCCESS';
export const HSN_LIST_FAILED = 'HSN_LIST_FAILED';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';

