/* HASHROOTSBILL */
export const HASHROOTSBILL_LIST = 'HASHROOTSBILL_LIST';
export const HASHROOTSBILL_LIST_SUCCESS = 'HASHROOTSBILL_LIST_SUCCESS';
export const HASHROOTSBILL_LIST_FAILED = 'HASHROOTSBILL_LIST_FAILED';

export const HASHROOTSBILL_ADD = 'HASHROOTSBILL_ADD';
export const HASHROOTSBILL_ADD_SUCCESS = 'HASHROOTSBILL_ADD_SUCCESS';
export const HASHROOTSBILL_ADD_FAILED = 'HASHROOTSBILLADD_ADD_FAILED';

export const HASHROOTSBILL_UPDATE = 'HASHROOTSBILL_UPDATE';
export const HASHROOTSBILL_UPDATE_SUCCESS = 'HASHROOTSBILL_UPDATE_SUCCESS';
export const HASHROOTSBILL_UPDATE_FAILED = 'HASHROOTSBILL_UPDATE_FAILED';

export const HASHROOTSBILL_DELETE = 'HASHROOTSBILL_DELETE';
export const HASHROOTSBILL_DELETE_SUCCESS = 'HASHROOTSBILL_DELETE_SUCCESS';
export const HASHROOTSBILL_DELETE_FAILED = 'HASHROOTSBILLADD_DELETE_FAILED';

export const HASHROOTSBILL_CLONE = 'HASHROOTSBILL_CLONE';
export const HASHROOTSBILL_CLONE_SUCCESS = 'HASHROOTSBILL_CLONE_SUCCESS';
export const HASHROOTSBILL_CLONE_FAILED = 'HASHROOTSBILL_CLONE_FAILED';

export const HASHROOTSBILL_DOWNLOAD_BILL = 'HASHROOTSBILL_DOWNLOAD_BILL';
export const HASHROOTSBILL_DOWNLOAD_BILL_SUCCESS = 'HASHROOTSBILL_DOWNLOAD_BILL_SUCCESS';
export const HASHROOTSBILL_DOWNLOAD_BILL_FAILED = 'HASHROOTSBILL_DOWNLOAD_BILL_FAILED';
